@Library("lab3") _
pipeline {
    agent {
        kubernetes {
             yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: build
    image: 'maven:3.8.3-jdk-11'
    command:
    - cat
    tty: true
    '''
        defaultContainer 'build'
        }
    }
    triggers {
        eventTrigger jmespathQuery("repository.url == 'https://github.com/dylanmeh/prudential_test'")
    }
    stages {
        stage('mvn version') {
            when {
                allOf {
                    triggeredBy 'EventTriggerCause';
                    equals (expected: 'https://github.com/dylanmeh/prudential_test', actual: getWebhookTriggerCauseEvent.getWebhookTriggerCauseEvent())
                }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage('condition based on repo url in payload') {
            when {
                allOf {
                    triggeredBy 'EventTriggerCause';
                    equals (expected: 'refs/heads/main', actual: getWebhookTriggerCauseEvent.getWebhookTriggerCauseEvent())
                }
            }
            steps {
                sh 'echo "running unit tests in main branch"'
            }
        }
    }
}